import pytest
from app.services.export_service import ExportService


class TestExportService:

    @pytest.fixture
    def export_service(self):
        return ExportService()

    def test_generate_markdown(self, export_service):
        paper = {
            "title": "Test Paper",
            "authors": ["Author 1", "Author 2"],
            "arxiv_id": "2301.12345",
            "source_url": "https://arxiv.org/abs/2301.12345",
            "pdf_url": "https://arxiv.org/pdf/2301.12345.pdf",
        }
        analysis = {
            "summary": {
                "quick": "Test summary",
                "eli5": "Test ELI5",
                "problem_and_motivation": "Why this paper exists",
                "method_deep_dive": "How the method works",
                "results_and_evidence": "The evidence is strong",
                "guided_walkthrough": "A longer walkthrough",
                "limitations_and_caveats": "A few caveats",
                "key_contributions": ["Contribution 1"],
                "key_findings": ["Finding 1"],
                "reader_takeaways": ["Takeaway 1"],
                "section_breakdown": [
                    {"title": "Method", "summary": "Section summary", "why_it_matters": "Why it matters"}
                ],
                "terms": [
                    {"term": "Agent", "category": "concept", "definition": "An acting system", "mentions": 2}
                ],
                "formula_explanations": [
                    {
                        "latex": "y = mx + b",
                        "plain_explanation": "A simple line.",
                        "symbols": {"m": "slope"},
                        "importance": "Defines the relationship"
                    }
                ],
                "figure_captions": [
                    {"label": "Figure 1", "caption": "System overview", "page": 0}
                ],
                "tables": [
                    {"title": "Table 1", "page": 1, "rows": [["Model", "Score"], ["A", "90"]]}
                ],
                "results_view": {
                    "evaluation_setup": "Compared against strong baselines on benchmark tasks.",
                    "results_summary": "The method improves headline metrics.",
                    "strongest_evidence": ["Table 1 shows the best overall score."],
                    "caveats": ["The gain is smaller on the hardest subset."],
                    "artifact_interpretations": [
                        {
                            "artifact_type": "table",
                            "label": "Table 1",
                            "section_title": "Results",
                            "what_it_shows": "Main benchmark comparison.",
                            "why_it_matters": "Demonstrates the claimed win.",
                            "confidence": "high",
                            "missing_context": "Per-dataset variance is not shown.",
                        }
                    ],
                },
            },
            "knowledge_graph": {
                "nodes": [
                    {"id": "agent", "label": "Agent", "category": "concept", "definition": "Acts in the environment", "value": 1}
                ],
                "edges": [
                    {"source": "agent", "target": "memory", "type": "uses", "weight": 1}
                ]
            },
        }

        md = export_service.generate_markdown(paper, analysis)

        assert "# Test Paper" in md
        assert "> Generated by PaperRelay" in md
        assert "**Authors:** Author 1, Author 2" in md
        assert "**Original paper:** https://arxiv.org/abs/2301.12345" in md
        assert "**Source PDF:** https://arxiv.org/pdf/2301.12345.pdf" in md
        assert "## Quick Summary" in md
        assert "## Evaluation Snapshot" in md
        assert "## Interpreted Evidence From Figures and Tables" in md
        assert "## ELI5" in md
        assert "## How the Paper Works" in md
        assert "## Results and Evidence" in md
        assert "## Guided Walkthrough" in md
        assert "## Limitations and Caveats" in md
        assert "## Key Findings" in md
        assert "## What to Remember" in md
        assert "## Section-by-Section Walkthrough" in md
        assert "## Key Terms to Know" in md
        assert "## Formula Explanations" in md
        assert "## Figures Mentioned in the Paper" in md
        assert "## Extracted Table Snapshots" in md
        assert "## Knowledge Graph" in md
        assert "### Key relationships" in md
        assert "**Confidence:** high" in md
        assert "**Missing context:** Per-dataset variance is not shown." in md

    def test_generate_markdown_missing_fields(self, export_service):
        """Test markdown generation with missing optional fields."""
        paper = {
            "title": "Test Paper",
            "authors": ["Author 1"],
            "arxiv_id": "2301.12345"
        }
        analysis = {
            "summary": {
                "quick": "Test summary"
            }
        }

        md = export_service.generate_markdown(paper, analysis)

        assert "# Test Paper" in md
        assert "**Authors:** Author 1" in md
        assert "## Quick Summary" in md
        assert "## ELI5" not in md  # ELI5 not present

    def test_generate_markdown_empty_paper(self, export_service):
        """Test markdown generation with empty paper data."""
        paper = {}
        analysis = {}

        md = export_service.generate_markdown(paper, analysis)

        assert "# Unknown" in md
        assert "**Authors:**" in md
        assert "**arXiv ID:**" in md

    def test_generate_pdf(self, export_service):
        """Test PDF generation returns bytes."""
        paper = {
            "title": "Test Paper",
            "authors": ["Author 1", "Author 2"],
            "arxiv_id": "2301.12345",
            "source_url": "https://arxiv.org/abs/2301.12345",
            "pdf_url": "https://arxiv.org/pdf/2301.12345.pdf",
        }
        analysis = {
            "summary": {
                "quick": "Test summary",
                "guided_walkthrough": "Longer walkthrough",
                "key_contributions": ["Contribution 1", "Contribution 2"],
                "results_view": {
                    "evaluation_setup": "Setup details",
                    "strongest_evidence": ["Table 1 is the strongest evidence"],
                    "artifact_interpretations": [
                        {
                            "artifact_type": "table",
                            "label": "Table 1",
                            "section_title": "Results",
                            "what_it_shows": "Main comparison",
                            "why_it_matters": "It supports the main claim",
                            "confidence": "medium",
                        }
                    ],
                },
                "formula_explanations": [
                    {
                        "latex": "y = mx + b",
                        "plain_explanation": "A simple line.",
                        "symbols": {"m": "slope"},
                        "importance": "Defines the relationship"
                    }
                ],
            },
            "knowledge_graph": {
                "nodes": [
                    {"id": "agent", "label": "Agent", "category": "concept", "definition": "Acts in the environment", "value": 1}
                ],
                "edges": [
                    {"source": "agent", "target": "memory", "type": "uses", "weight": 1}
                ]
            },
        }

        pdf_bytes = export_service.generate_pdf(paper, analysis)

        assert isinstance(pdf_bytes, bytes)
        assert len(pdf_bytes) > 0
        # PDF files start with %PDF
        assert pdf_bytes.startswith(b'%PDF')

    def test_generate_pdf_empty_data(self, export_service):
        """Test PDF generation with empty data."""
        paper = {}
        analysis = {}

        pdf_bytes = export_service.generate_pdf(paper, analysis)

        assert isinstance(pdf_bytes, bytes)
        assert len(pdf_bytes) > 0
