from io import BytesIO
from typing import Any, Dict, Iterable, List, Optional
from xml.sax.saxutils import escape

from reportlab.lib import colors, pagesizes
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer

from app.schemas.paper import (
    AnalysisSummary,
    ArtifactInterpretation,
    DistilledSection,
    DistilledTerm,
    ExtractedTable,
    FigureCaption,
    FormulaExplanation,
    ResultsView,
)


class ExportService:
    """Service for exporting paper analyses."""

    def generate_pdf(
        self,
        paper: Dict[str, Any],
        summary: Optional[AnalysisSummary],
        knowledge_graph: Optional[Dict[str, Any]],
    ) -> bytes:
        """Generate PDF export of paper analysis."""
        buffer = BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=pagesizes.letter,
            rightMargin=0.75 * inch,
            leftMargin=0.75 * inch,
            topMargin=0.75 * inch,
            bottomMargin=0.75 * inch,
        )

        styles = self._build_pdf_styles()
        story: List[Any] = []

        self._append_pdf_title_block(story, styles, paper)

        knowledge_graph = knowledge_graph or {}
        results_view = summary.results_view if summary else None
        artifact_interpretations = (
            summary.artifact_interpretations or (results_view.artifact_interpretations if results_view else [])
        ) if summary else []

        if summary:
            self._append_pdf_section(story, styles, "Quick Summary", summary.quick)
            self._append_pdf_section(story, styles, "Problem and Motivation", summary.problem_and_motivation)
            self._append_pdf_section(story, styles, "How the Paper Works", summary.method_deep_dive or summary.technical)
            self._append_pdf_section(story, styles, "Results and Evidence", summary.results_and_evidence)
            self._append_pdf_results_view(story, styles, "Evaluation Snapshot", results_view)
            self._append_pdf_artifact_interpretations(story, styles, "Interpreted Evidence From Figures and Tables", artifact_interpretations)
            self._append_pdf_section(story, styles, "Guided Walkthrough", summary.guided_walkthrough)
            self._append_pdf_section(story, styles, "Explain It Simply", summary.eli5)
            self._append_pdf_section(story, styles, "Limitations and Caveats", summary.limitations_and_caveats)

            self._append_pdf_list_section(story, styles, "Key Contributions", summary.key_contributions)
            self._append_pdf_list_section(story, styles, "Key Findings", summary.key_findings)
            self._append_pdf_list_section(story, styles, "What to Remember", summary.reader_takeaways)
            self._append_pdf_section_cards(story, styles, "Section-by-Section Walkthrough", summary.section_breakdown)
            self._append_pdf_term_cards(story, styles, "Key Terms to Know", summary.terms)
            self._append_pdf_formula_section(story, styles, "Formula Explanations", summary.formula_explanations)
            self._append_pdf_figure_section(story, styles, "Figures Mentioned in the Paper", summary.figure_captions)
            self._append_pdf_table_section(story, styles, "Extracted Table Snapshots", summary.tables)

        self._append_pdf_graph_section(story, styles, "Knowledge Graph", knowledge_graph)

        doc.build(story)
        buffer.seek(0)
        return buffer.getvalue()

    def generate_markdown(
        self,
        paper: Dict[str, Any],
        summary: Optional[AnalysisSummary],
        knowledge_graph: Optional[Dict[str, Any]],
    ) -> str:
        """Generate Markdown export of paper analysis."""
        source_url = self._paper_source_url(paper)
        pdf_url = paper.get("pdf_url")
        lines = [
            "> Generated by PaperRelay",
            "",
            f"# {paper.get('title', 'Unknown')}",
            "",
            f"**Authors:** {', '.join(paper.get('authors', []))}  ",
            f"**arXiv ID:** {paper.get('arxiv_id', '')}  ",
        ]
        if source_url:
            lines.append(f"**Original paper:** {source_url}  ")
        if pdf_url:
            lines.append(f"**Source PDF:** {pdf_url}  ")
        lines.extend([
            "",
            "---",
            "",
        ])

        knowledge_graph = knowledge_graph or {}
        results_view = summary.results_view if summary else None
        artifact_interpretations = (
            summary.artifact_interpretations or (results_view.artifact_interpretations if results_view else [])
        ) if summary else []

        if summary:
            self._append_markdown_section(lines, "Quick Summary", summary.quick)
            self._append_markdown_section(lines, "Problem and Motivation", summary.problem_and_motivation)
            self._append_markdown_section(lines, "How the Paper Works", summary.method_deep_dive or summary.technical)
            self._append_markdown_section(lines, "Results and Evidence", summary.results_and_evidence)
            self._append_markdown_results_view(lines, "Evaluation Snapshot", results_view)
            self._append_markdown_artifact_interpretations(lines, "Interpreted Evidence From Figures and Tables", artifact_interpretations)
            self._append_markdown_section(lines, "Guided Walkthrough", summary.guided_walkthrough)
            self._append_markdown_section(lines, "ELI5", summary.eli5)
            self._append_markdown_section(lines, "Limitations and Caveats", summary.limitations_and_caveats)

            self._append_markdown_list_section(lines, "Key Contributions", summary.key_contributions)
            self._append_markdown_list_section(lines, "Key Findings", summary.key_findings)
            self._append_markdown_list_section(lines, "What to Remember", summary.reader_takeaways)
            self._append_markdown_section_breakdown(lines, "Section-by-Section Walkthrough", summary.section_breakdown)
            self._append_markdown_terms(lines, "Key Terms to Know", summary.terms)
            self._append_markdown_formulas(lines, "Formula Explanations", summary.formula_explanations)
            self._append_markdown_figures(lines, "Figures Mentioned in the Paper", summary.figure_captions)
            self._append_markdown_tables(lines, "Extracted Table Snapshots", summary.tables)

        self._append_markdown_graph(lines, "Knowledge Graph", knowledge_graph)

        return "\n".join(lines).strip() + "\n"

    def _build_pdf_styles(self) -> Any:
        styles = getSampleStyleSheet()
        styles.add(
            ParagraphStyle(
                name="CustomHeading",
                parent=styles["Heading1"],
                textColor=colors.HexColor("#1976d2"),
                fontSize=18,
                leading=22,
            )
        )
        styles.add(
            ParagraphStyle(
                name="SubHeading",
                parent=styles["Heading2"],
                fontSize=14,
                leading=18,
            )
        )
        styles.add(
            ParagraphStyle(
                name="ExportBodyText",
                parent=styles["Normal"],
                fontSize=11,
                leading=16,
            )
        )
        styles.add(
            ParagraphStyle(
                name="ExportMetaText",
                parent=styles["Normal"],
                fontSize=10,
                leading=14,
                textColor=colors.HexColor("#5f6b7a"),
            )
        )
        styles.add(
            ParagraphStyle(
                name="BrandHeading",
                parent=styles["Heading2"],
                fontSize=12,
                leading=16,
                textColor=colors.HexColor("#173b7a"),
                spaceAfter=6,
            )
        )
        return styles

    def _append_pdf_title_block(self, story: List[Any], styles: Any, paper: Dict[str, Any]) -> None:
        source_url = self._paper_source_url(paper)
        pdf_url = paper.get("pdf_url")
        story.append(Paragraph("<b>PaperRelay Distillation Export</b>", styles["BrandHeading"]))
        story.append(Paragraph(f"<b>{escape(paper.get('title', 'Unknown'))}</b>", styles["CustomHeading"]))
        story.append(Spacer(1, 0.2 * inch))
        story.append(
            Paragraph(
                f"<b>Authors:</b> {escape(', '.join(paper.get('authors', [])))}",
                styles["ExportBodyText"],
            )
        )
        story.append(
            Paragraph(
                f"<b>arXiv ID:</b> {escape(paper.get('arxiv_id', ''))}",
                styles["ExportBodyText"],
            )
        )
        if source_url:
            story.append(
                Paragraph(
                    f"<b>Original paper:</b> {escape(source_url)}",
                    styles["ExportMetaText"],
                )
            )
        if pdf_url:
            story.append(
                Paragraph(
                    f"<b>Source PDF:</b> {escape(str(pdf_url))}",
                    styles["ExportMetaText"],
                )
            )
        story.append(Spacer(1, 0.3 * inch))

    def _append_pdf_section(self, story: List[Any], styles: Any, heading: str, content: Optional[str]) -> None:
        if not content:
            return
        story.append(Paragraph(f"<b>{escape(heading)}</b>", styles["SubHeading"]))
        for paragraph in self._paragraphs(content):
            story.append(Paragraph(escape(paragraph), styles["ExportBodyText"]))
            story.append(Spacer(1, 0.08 * inch))
        story.append(Spacer(1, 0.08 * inch))

    def _append_pdf_list_section(self, story: List[Any], styles: Any, heading: str, items: Optional[Iterable[str]]) -> None:
        normalized = [item.strip() for item in (items or []) if item and item.strip()]
        if not normalized:
            return
        story.append(Paragraph(f"<b>{escape(heading)}</b>", styles["SubHeading"]))
        for item in normalized:
            story.append(Paragraph(f"• {escape(item)}", styles["ExportBodyText"]))
        story.append(Spacer(1, 0.12 * inch))

    def _append_pdf_section_cards(
        self,
        story: List[Any],
        styles: Any,
        heading: str,
        sections: Optional[List[DistilledSection]],
    ) -> None:
        normalized = [section for section in (sections or []) if section.title or section.summary]
        if not normalized:
            return
        story.append(Paragraph(f"<b>{escape(heading)}</b>", styles["SubHeading"]))
        for section in normalized:
            title = section.title or "Untitled section"
            story.append(Paragraph(f"<b>{escape(title)}</b>", styles["ExportBodyText"]))
            if section.summary:
                for paragraph in self._paragraphs(section.summary):
                    story.append(Paragraph(escape(paragraph), styles["ExportBodyText"]))
            if section.why_it_matters:
                story.append(
                    Paragraph(
                        f"<b>Why it matters:</b> {escape(section.why_it_matters)}",
                        styles["ExportBodyText"],
                    )
                )
            story.append(Spacer(1, 0.1 * inch))
        story.append(Spacer(1, 0.08 * inch))

    def _append_pdf_term_cards(
        self,
        story: List[Any],
        styles: Any,
        heading: str,
        terms: Optional[List[DistilledTerm]],
    ) -> None:
        normalized = [term for term in (terms or []) if term.term]
        if not normalized:
            return
        story.append(Paragraph(f"<b>{escape(heading)}</b>", styles["SubHeading"]))
        for term in normalized:
            label = term.term
            category = term.category
            title = label if not category else f"{label} ({category})"
            story.append(Paragraph(f"<b>{escape(title)}</b>", styles["ExportBodyText"]))
            if term.definition:
                story.append(Paragraph(escape(term.definition), styles["ExportBodyText"]))
            story.append(Spacer(1, 0.08 * inch))
        story.append(Spacer(1, 0.08 * inch))

    def _append_pdf_formula_section(
        self,
        story: List[Any],
        styles: Any,
        heading: str,
        formulas: Optional[List[FormulaExplanation]],
    ) -> None:
        normalized = [formula for formula in (formulas or []) if formula.latex or formula.plain_explanation]
        if not normalized:
            return
        story.append(Paragraph(f"<b>{escape(heading)}</b>", styles["SubHeading"]))
        for formula in normalized:
            if formula.latex:
                story.append(
                    Paragraph(
                        f"<b>Expression:</b> {escape(formula.latex)}",
                        styles["ExportBodyText"],
                    )
                )
            if formula.plain_explanation:
                story.append(Paragraph(escape(formula.plain_explanation), styles["ExportBodyText"]))
            symbols = formula.symbols or {}
            for symbol, meaning in symbols.items():
                story.append(
                    Paragraph(
                        f"• {escape(str(symbol))}: {escape(str(meaning))}",
                        styles["ExportMetaText"],
                    )
                )
            if formula.importance:
                story.append(
                    Paragraph(
                        f"<b>Why it matters:</b> {escape(formula.importance)}",
                        styles["ExportBodyText"],
                    )
                )
            story.append(Spacer(1, 0.1 * inch))
        story.append(Spacer(1, 0.08 * inch))

    def _append_pdf_results_view(
        self,
        story: List[Any],
        styles: Any,
        heading: str,
        results_view: Optional[ResultsView],
    ) -> None:
        if not results_view:
            return
        has_content = any(
            value
            for value in (
                results_view.evaluation_setup,
                results_view.results_summary,
                results_view.strongest_evidence,
                results_view.caveats,
            )
        )
        if not has_content:
            return

        story.append(Paragraph(f"<b>{escape(heading)}</b>", styles["SubHeading"]))
        if results_view.evaluation_setup:
            story.append(
                Paragraph(
                    f"<b>Evaluation setup:</b> {escape(str(results_view.evaluation_setup))}",
                    styles["ExportBodyText"],
                )
            )
        if results_view.results_summary:
            story.append(
                Paragraph(
                    f"<b>What the evidence says:</b> {escape(str(results_view.results_summary))}",
                    styles["ExportBodyText"],
                )
            )
        strongest_evidence = [item for item in results_view.strongest_evidence if item]
        if strongest_evidence:
            story.append(Paragraph("<b>Strongest evidence</b>", styles["ExportBodyText"]))
            for item in strongest_evidence:
                story.append(Paragraph(f"• {escape(str(item))}", styles["ExportMetaText"]))
        caveats = [item for item in results_view.caveats if item]
        if caveats:
            story.append(Paragraph("<b>Evidence caveats</b>", styles["ExportBodyText"]))
            for item in caveats:
                story.append(Paragraph(f"• {escape(str(item))}", styles["ExportMetaText"]))
        story.append(Spacer(1, 0.12 * inch))

    def _append_pdf_artifact_interpretations(
        self,
        story: List[Any],
        styles: Any,
        heading: str,
        items: Optional[List[ArtifactInterpretation]],
    ) -> None:
        normalized = [item for item in (items or []) if item.what_it_shows or item.why_it_matters]
        if not normalized:
            return
        story.append(Paragraph(f"<b>{escape(heading)}</b>", styles["SubHeading"]))
        for item in normalized:
            label = item.label or item.artifact_type or "Artifact"
            artifact_type = item.artifact_type
            section_title = item.section_title
            confidence = item.confidence
            title_parts = [str(label)]
            if artifact_type:
                title_parts.append(f"({artifact_type})")
            story.append(Paragraph(f"<b>{escape(' '.join(title_parts))}</b>", styles["ExportBodyText"]))
            meta_parts = []
            if section_title:
                meta_parts.append(f"Section: {section_title}")
            if confidence:
                meta_parts.append(f"Confidence: {confidence}")
            if meta_parts:
                story.append(Paragraph(escape(" | ".join(meta_parts)), styles["ExportMetaText"]))
            if item.what_it_shows:
                story.append(
                    Paragraph(
                        f"<b>What it shows:</b> {escape(str(item.what_it_shows))}",
                        styles["ExportBodyText"],
                    )
                )
            if item.why_it_matters:
                story.append(
                    Paragraph(
                        f"<b>Why it matters:</b> {escape(str(item.why_it_matters))}",
                        styles["ExportBodyText"],
                    )
                )
            missing_context = getattr(item, "missing_context", None)
            if missing_context:
                story.append(
                    Paragraph(
                        f"<b>Missing context:</b> {escape(str(missing_context))}",
                        styles["ExportMetaText"],
                    )
                )
            story.append(Spacer(1, 0.1 * inch))
        story.append(Spacer(1, 0.08 * inch))

    def _append_pdf_figure_section(
        self,
        story: List[Any],
        styles: Any,
        heading: str,
        figures: Optional[List[FigureCaption]],
    ) -> None:
        normalized = [figure for figure in (figures or []) if figure.caption]
        if not normalized:
            return
        story.append(Paragraph(f"<b>{escape(heading)}</b>", styles["SubHeading"]))
        for figure in normalized:
            label = figure.label or "Figure"
            page = figure.page
            page_suffix = f" (page {page + 1})" if isinstance(page, int) else ""
            story.append(
                Paragraph(
                    f"<b>{escape(str(label))}{escape(page_suffix)}:</b> {escape(figure.caption)}",
                    styles["ExportBodyText"],
                )
            )
        story.append(Spacer(1, 0.12 * inch))

    def _append_pdf_table_section(
        self,
        story: List[Any],
        styles: Any,
        heading: str,
        tables: Optional[List[ExtractedTable]],
    ) -> None:
        normalized = [table for table in (tables or []) if table.rows]
        if not normalized:
            return
        story.append(Paragraph(f"<b>{escape(heading)}</b>", styles["SubHeading"]))
        for table in normalized:
            title = table.title or "Table"
            page = table.page
            page_suffix = f" (page {page + 1})" if isinstance(page, int) else ""
            story.append(Paragraph(f"<b>{escape(title)}{escape(page_suffix)}</b>", styles["ExportBodyText"]))
            preview_rows = table.rows[:6]
            for row in preview_rows:
                row_text = " | ".join((cell or "—").strip() for cell in row)
                story.append(Paragraph(escape(row_text), styles["ExportMetaText"]))
            story.append(Spacer(1, 0.08 * inch))
        story.append(Spacer(1, 0.08 * inch))

    def _append_pdf_graph_section(self, story: List[Any], styles: Any, heading: str, knowledge_graph: Dict[str, Any]) -> None:
        nodes = knowledge_graph.get("nodes") or []
        edges = knowledge_graph.get("edges") or []
        if not nodes and not edges:
            return

        story.append(Paragraph(f"<b>{escape(heading)}</b>", styles["SubHeading"]))
        if nodes:
            story.append(Paragraph("<b>Key concepts</b>", styles["ExportBodyText"]))
            for node in nodes[:12]:
                label = node.get("label") or node.get("id") or "Concept"
                category = node.get("category")
                definition = node.get("definition")
                title = label if not category else f"{label} ({category})"
                story.append(Paragraph(f"• {escape(title)}", styles["ExportBodyText"]))
                if definition:
                    story.append(Paragraph(escape(definition), styles["ExportMetaText"]))
        if edges:
            story.append(Spacer(1, 0.08 * inch))
            story.append(Paragraph("<b>Key relationships</b>", styles["ExportBodyText"]))
            for edge in edges[:16]:
                source = edge.get("source", "source")
                relation = edge.get("type", "relates to")
                target = edge.get("target", "target")
                story.append(
                    Paragraph(
                        f"• {escape(str(source))} {escape(str(relation))} {escape(str(target))}",
                        styles["ExportMetaText"],
                    )
                )
        story.append(Spacer(1, 0.12 * inch))

    def _append_markdown_section(self, lines: List[str], heading: str, content: Optional[str]) -> None:
        if not content:
            return
        lines.extend([f"## {heading}", "", content.strip(), ""])

    def _append_markdown_list_section(self, lines: List[str], heading: str, items: Optional[Iterable[str]]) -> None:
        normalized = [item.strip() for item in (items or []) if item and item.strip()]
        if not normalized:
            return
        lines.extend([f"## {heading}", ""])
        lines.extend([f"- {item}" for item in normalized])
        lines.append("")

    def _append_markdown_section_breakdown(
        self,
        lines: List[str],
        heading: str,
        sections: Optional[List[DistilledSection]],
    ) -> None:
        normalized = [section for section in (sections or []) if section.title or section.summary]
        if not normalized:
            return
        lines.extend([f"## {heading}", ""])
        for section in normalized:
            lines.append(f"### {section.title or 'Untitled section'}")
            lines.append("")
            if section.summary:
                lines.append(section.summary.strip())
                lines.append("")
            if section.why_it_matters:
                lines.append(f"**Why it matters:** {section.why_it_matters.strip()}")
                lines.append("")

    def _append_markdown_terms(
        self,
        lines: List[str],
        heading: str,
        terms: Optional[List[DistilledTerm]],
    ) -> None:
        normalized = [term for term in (terms or []) if term.term]
        if not normalized:
            return
        lines.extend([f"## {heading}", ""])
        for term in normalized:
            category = f" ({term.category})" if term.category else ""
            lines.append(f"- **{term.term}**{category}: {term.definition.strip()}")
        lines.append("")

    def _append_markdown_formulas(
        self,
        lines: List[str],
        heading: str,
        formulas: Optional[List[FormulaExplanation]],
    ) -> None:
        normalized = [formula for formula in (formulas or []) if formula.latex or formula.plain_explanation]
        if not normalized:
            return
        lines.extend([f"## {heading}", ""])
        for formula in normalized:
            if formula.latex:
                lines.append(f"### `{formula.latex}`")
                lines.append("")
            if formula.plain_explanation:
                lines.append(formula.plain_explanation.strip())
                lines.append("")
            symbols = formula.symbols or {}
            if symbols:
                lines.append("**Symbols**")
                lines.append("")
                for symbol, meaning in symbols.items():
                    lines.append(f"- `{symbol}`: {meaning}")
                lines.append("")
            if formula.importance:
                lines.append(f"**Why it matters:** {formula.importance.strip()}")
                lines.append("")

    def _append_markdown_results_view(
        self,
        lines: List[str],
        heading: str,
        results_view: Optional[ResultsView],
    ) -> None:
        if not results_view:
            return
        has_content = any(
            value
            for value in (
                results_view.evaluation_setup,
                results_view.results_summary,
                results_view.strongest_evidence,
                results_view.caveats,
            )
        )
        if not has_content:
            return

        lines.extend([f"## {heading}", ""])
        if results_view.evaluation_setup:
            lines.append(f"**Evaluation setup:** {str(results_view.evaluation_setup).strip()}")
            lines.append("")
        if results_view.results_summary:
            lines.append(f"**What the evidence says:** {str(results_view.results_summary).strip()}")
            lines.append("")
        strongest_evidence = [item for item in results_view.strongest_evidence if item]
        if strongest_evidence:
            lines.append("### Strongest evidence")
            lines.append("")
            lines.extend([f"- {str(item).strip()}" for item in strongest_evidence])
            lines.append("")
        caveats = [item for item in results_view.caveats if item]
        if caveats:
            lines.append("### Evidence caveats")
            lines.append("")
            lines.extend([f"- {str(item).strip()}" for item in caveats])
            lines.append("")

    def _append_markdown_artifact_interpretations(
        self,
        lines: List[str],
        heading: str,
        items: Optional[List[ArtifactInterpretation]],
    ) -> None:
        normalized = [item for item in (items or []) if item.what_it_shows or item.why_it_matters]
        if not normalized:
            return
        lines.extend([f"## {heading}", ""])
        for item in normalized:
            label = item.label or item.artifact_type or "Artifact"
            artifact_type = f" ({item.artifact_type})" if item.artifact_type else ""
            lines.append(f"### {label}{artifact_type}")
            lines.append("")
            if item.section_title:
                lines.append(f"**Section:** {str(item.section_title).strip()}")
                lines.append("")
            if item.confidence:
                lines.append(f"**Confidence:** {str(item.confidence).strip()}")
                lines.append("")
            if item.what_it_shows:
                lines.append(f"**What it shows:** {str(item.what_it_shows).strip()}")
                lines.append("")
            if item.why_it_matters:
                lines.append(f"**Why it matters:** {str(item.why_it_matters).strip()}")
                lines.append("")
            missing_context = getattr(item, "missing_context", None)
            if missing_context:
                lines.append(f"**Missing context:** {str(missing_context).strip()}")
                lines.append("")

    def _append_markdown_figures(
        self,
        lines: List[str],
        heading: str,
        figures: Optional[List[FigureCaption]],
    ) -> None:
        normalized = [figure for figure in (figures or []) if figure.caption]
        if not normalized:
            return
        lines.extend([f"## {heading}", ""])
        for figure in normalized:
            label = figure.label or "Figure"
            page = figure.page
            page_suffix = f" (page {page + 1})" if isinstance(page, int) else ""
            lines.append(f"- **{label}{page_suffix}:** {figure.caption}")
        lines.append("")

    def _append_markdown_tables(
        self,
        lines: List[str],
        heading: str,
        tables: Optional[List[ExtractedTable]],
    ) -> None:
        normalized = [table for table in (tables or []) if table.rows]
        if not normalized:
            return
        lines.extend([f"## {heading}", ""])
        for table in normalized:
            title = table.title or "Table"
            page = table.page
            page_suffix = f" (page {page + 1})" if isinstance(page, int) else ""
            lines.append(f"### {title}{page_suffix}")
            lines.append("")
            preview_rows = table.rows[:6]
            for row in preview_rows:
                lines.append(f"- {' | '.join((cell or '—').strip() for cell in row)}")
            lines.append("")

    def _append_markdown_graph(self, lines: List[str], heading: str, knowledge_graph: Dict[str, Any]) -> None:
        nodes = knowledge_graph.get("nodes") or []
        edges = knowledge_graph.get("edges") or []
        if not nodes and not edges:
            return
        lines.extend([f"## {heading}", ""])
        if nodes:
            lines.extend(["### Key concepts", ""])
            for node in nodes[:12]:
                label = node.get("label") or node.get("id") or "Concept"
                category = f" ({node['category']})" if node.get("category") else ""
                definition = f": {node['definition']}" if node.get("definition") else ""
                lines.append(f"- **{label}**{category}{definition}")
            lines.append("")
        if edges:
            lines.extend(["### Key relationships", ""])
            for edge in edges[:16]:
                lines.append(f"- `{edge.get('source', 'source')}` {edge.get('type', 'relates to')} `{edge.get('target', 'target')}`")
            lines.append("")

    def _paragraphs(self, content: str) -> List[str]:
        return [paragraph.strip() for paragraph in content.split("\n") if paragraph.strip()]

    def _paper_source_url(self, paper: Dict[str, Any]) -> Optional[str]:
        if paper.get("source_url"):
            return str(paper["source_url"])
        arxiv_id = (paper.get("arxiv_id") or "").strip()
        if arxiv_id:
            return f"https://arxiv.org/abs/{arxiv_id}"
        return None
