from io import BytesIO
from typing import Any, Dict, Iterable, List, Optional
from xml.sax.saxutils import escape

from reportlab.lib import colors, pagesizes
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer


class ExportService:
    """Service for exporting paper analyses."""

    def generate_pdf(self, paper: Dict[str, Any], analysis: Dict[str, Any]) -> bytes:
        """Generate PDF export of paper analysis."""
        buffer = BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=pagesizes.letter,
            rightMargin=0.75 * inch,
            leftMargin=0.75 * inch,
            topMargin=0.75 * inch,
            bottomMargin=0.75 * inch,
        )

        styles = self._build_pdf_styles()
        story: List[Any] = []

        self._append_pdf_title_block(story, styles, paper)

        summary = analysis.get("summary") or {}
        knowledge_graph = analysis.get("knowledge_graph") or {}
        results_view = summary.get("results_view") or {}
        artifact_interpretations = summary.get("artifact_interpretations") or results_view.get("artifact_interpretations")

        if summary:
            self._append_pdf_section(story, styles, "Quick Summary", summary.get("quick"))
            self._append_pdf_section(story, styles, "Problem and Motivation", summary.get("problem_and_motivation"))
            self._append_pdf_section(story, styles, "How the Paper Works", summary.get("method_deep_dive") or summary.get("technical"))
            self._append_pdf_section(story, styles, "Results and Evidence", summary.get("results_and_evidence"))
            self._append_pdf_results_view(story, styles, "Evaluation Snapshot", results_view)
            self._append_pdf_artifact_interpretations(story, styles, "Interpreted Evidence From Figures and Tables", artifact_interpretations)
            self._append_pdf_section(story, styles, "Guided Walkthrough", summary.get("guided_walkthrough"))
            self._append_pdf_section(story, styles, "Explain It Simply", summary.get("eli5"))
            self._append_pdf_section(story, styles, "Limitations and Caveats", summary.get("limitations_and_caveats"))

            self._append_pdf_list_section(story, styles, "Key Contributions", summary.get("key_contributions"))
            self._append_pdf_list_section(story, styles, "Key Findings", summary.get("key_findings"))
            self._append_pdf_list_section(story, styles, "What to Remember", summary.get("reader_takeaways"))
            self._append_pdf_section_cards(story, styles, "Section-by-Section Walkthrough", summary.get("section_breakdown"))
            self._append_pdf_term_cards(story, styles, "Key Terms to Know", summary.get("terms"))
            self._append_pdf_formula_section(story, styles, "Formula Explanations", summary.get("formula_explanations"))
            self._append_pdf_figure_section(story, styles, "Figures Mentioned in the Paper", summary.get("figure_captions"))
            self._append_pdf_table_section(story, styles, "Extracted Table Snapshots", summary.get("tables"))

        self._append_pdf_graph_section(story, styles, "Knowledge Graph", knowledge_graph)

        doc.build(story)
        buffer.seek(0)
        return buffer.getvalue()

    def generate_markdown(self, paper: Dict[str, Any], analysis: Dict[str, Any]) -> str:
        """Generate Markdown export of paper analysis."""
        source_url = self._paper_source_url(paper)
        pdf_url = paper.get("pdf_url")
        lines = [
            "> Generated by PaperRelay",
            "",
            f"# {paper.get('title', 'Unknown')}",
            "",
            f"**Authors:** {', '.join(paper.get('authors', []))}  ",
            f"**arXiv ID:** {paper.get('arxiv_id', '')}  ",
        ]
        if source_url:
            lines.append(f"**Original paper:** {source_url}  ")
        if pdf_url:
            lines.append(f"**Source PDF:** {pdf_url}  ")
        lines.extend([
            "",
            "---",
            "",
        ])

        summary = analysis.get("summary") or {}
        knowledge_graph = analysis.get("knowledge_graph") or {}
        results_view = summary.get("results_view") or {}
        artifact_interpretations = summary.get("artifact_interpretations") or results_view.get("artifact_interpretations")

        if summary:
            self._append_markdown_section(lines, "Quick Summary", summary.get("quick"))
            self._append_markdown_section(lines, "Problem and Motivation", summary.get("problem_and_motivation"))
            self._append_markdown_section(lines, "How the Paper Works", summary.get("method_deep_dive") or summary.get("technical"))
            self._append_markdown_section(lines, "Results and Evidence", summary.get("results_and_evidence"))
            self._append_markdown_results_view(lines, "Evaluation Snapshot", results_view)
            self._append_markdown_artifact_interpretations(lines, "Interpreted Evidence From Figures and Tables", artifact_interpretations)
            self._append_markdown_section(lines, "Guided Walkthrough", summary.get("guided_walkthrough"))
            self._append_markdown_section(lines, "ELI5", summary.get("eli5"))
            self._append_markdown_section(lines, "Limitations and Caveats", summary.get("limitations_and_caveats"))

            self._append_markdown_list_section(lines, "Key Contributions", summary.get("key_contributions"))
            self._append_markdown_list_section(lines, "Key Findings", summary.get("key_findings"))
            self._append_markdown_list_section(lines, "What to Remember", summary.get("reader_takeaways"))
            self._append_markdown_section_breakdown(lines, "Section-by-Section Walkthrough", summary.get("section_breakdown"))
            self._append_markdown_terms(lines, "Key Terms to Know", summary.get("terms"))
            self._append_markdown_formulas(lines, "Formula Explanations", summary.get("formula_explanations"))
            self._append_markdown_figures(lines, "Figures Mentioned in the Paper", summary.get("figure_captions"))
            self._append_markdown_tables(lines, "Extracted Table Snapshots", summary.get("tables"))

        self._append_markdown_graph(lines, "Knowledge Graph", knowledge_graph)

        return "\n".join(lines).strip() + "\n"

    def _build_pdf_styles(self) -> Any:
        styles = getSampleStyleSheet()
        styles.add(
            ParagraphStyle(
                name="CustomHeading",
                parent=styles["Heading1"],
                textColor=colors.HexColor("#1976d2"),
                fontSize=18,
                leading=22,
            )
        )
        styles.add(
            ParagraphStyle(
                name="SubHeading",
                parent=styles["Heading2"],
                fontSize=14,
                leading=18,
            )
        )
        styles.add(
            ParagraphStyle(
                name="ExportBodyText",
                parent=styles["Normal"],
                fontSize=11,
                leading=16,
            )
        )
        styles.add(
            ParagraphStyle(
                name="ExportMetaText",
                parent=styles["Normal"],
                fontSize=10,
                leading=14,
                textColor=colors.HexColor("#5f6b7a"),
            )
        )
        styles.add(
            ParagraphStyle(
                name="BrandHeading",
                parent=styles["Heading2"],
                fontSize=12,
                leading=16,
                textColor=colors.HexColor("#173b7a"),
                spaceAfter=6,
            )
        )
        return styles

    def _append_pdf_title_block(self, story: List[Any], styles: Any, paper: Dict[str, Any]) -> None:
        source_url = self._paper_source_url(paper)
        pdf_url = paper.get("pdf_url")
        story.append(Paragraph("<b>PaperRelay Distillation Export</b>", styles["BrandHeading"]))
        story.append(Paragraph(f"<b>{escape(paper.get('title', 'Unknown'))}</b>", styles["CustomHeading"]))
        story.append(Spacer(1, 0.2 * inch))
        story.append(
            Paragraph(
                f"<b>Authors:</b> {escape(', '.join(paper.get('authors', [])))}",
                styles["ExportBodyText"],
            )
        )
        story.append(
            Paragraph(
                f"<b>arXiv ID:</b> {escape(paper.get('arxiv_id', ''))}",
                styles["ExportBodyText"],
            )
        )
        if source_url:
            story.append(
                Paragraph(
                    f"<b>Original paper:</b> {escape(source_url)}",
                    styles["ExportMetaText"],
                )
            )
        if pdf_url:
            story.append(
                Paragraph(
                    f"<b>Source PDF:</b> {escape(str(pdf_url))}",
                    styles["ExportMetaText"],
                )
            )
        story.append(Spacer(1, 0.3 * inch))

    def _append_pdf_section(self, story: List[Any], styles: Any, heading: str, content: Optional[str]) -> None:
        if not content:
            return
        story.append(Paragraph(f"<b>{escape(heading)}</b>", styles["SubHeading"]))
        for paragraph in self._paragraphs(content):
            story.append(Paragraph(escape(paragraph), styles["ExportBodyText"]))
            story.append(Spacer(1, 0.08 * inch))
        story.append(Spacer(1, 0.08 * inch))

    def _append_pdf_list_section(self, story: List[Any], styles: Any, heading: str, items: Optional[Iterable[str]]) -> None:
        normalized = [item.strip() for item in (items or []) if item and item.strip()]
        if not normalized:
            return
        story.append(Paragraph(f"<b>{escape(heading)}</b>", styles["SubHeading"]))
        for item in normalized:
            story.append(Paragraph(f"• {escape(item)}", styles["ExportBodyText"]))
        story.append(Spacer(1, 0.12 * inch))

    def _append_pdf_section_cards(self, story: List[Any], styles: Any, heading: str, sections: Optional[List[Dict[str, Any]]]) -> None:
        normalized = [section for section in (sections or []) if section.get("title") or section.get("summary")]
        if not normalized:
            return
        story.append(Paragraph(f"<b>{escape(heading)}</b>", styles["SubHeading"]))
        for section in normalized:
            title = section.get("title", "Untitled section")
            story.append(Paragraph(f"<b>{escape(title)}</b>", styles["ExportBodyText"]))
            if section.get("summary"):
                for paragraph in self._paragraphs(section["summary"]):
                    story.append(Paragraph(escape(paragraph), styles["ExportBodyText"]))
            if section.get("why_it_matters"):
                story.append(
                    Paragraph(
                        f"<b>Why it matters:</b> {escape(section['why_it_matters'])}",
                        styles["ExportBodyText"],
                    )
                )
            story.append(Spacer(1, 0.1 * inch))
        story.append(Spacer(1, 0.08 * inch))

    def _append_pdf_term_cards(self, story: List[Any], styles: Any, heading: str, terms: Optional[List[Dict[str, Any]]]) -> None:
        normalized = [term for term in (terms or []) if term.get("term")]
        if not normalized:
            return
        story.append(Paragraph(f"<b>{escape(heading)}</b>", styles["SubHeading"]))
        for term in normalized:
            label = term.get("term", "")
            category = term.get("category")
            title = label if not category else f"{label} ({category})"
            story.append(Paragraph(f"<b>{escape(title)}</b>", styles["ExportBodyText"]))
            if term.get("definition"):
                story.append(Paragraph(escape(term["definition"]), styles["ExportBodyText"]))
            story.append(Spacer(1, 0.08 * inch))
        story.append(Spacer(1, 0.08 * inch))

    def _append_pdf_formula_section(self, story: List[Any], styles: Any, heading: str, formulas: Optional[List[Dict[str, Any]]]) -> None:
        normalized = [formula for formula in (formulas or []) if formula.get("latex") or formula.get("plain_explanation")]
        if not normalized:
            return
        story.append(Paragraph(f"<b>{escape(heading)}</b>", styles["SubHeading"]))
        for formula in normalized:
            if formula.get("latex"):
                story.append(
                    Paragraph(
                        f"<b>Expression:</b> {escape(formula['latex'])}",
                        styles["ExportBodyText"],
                    )
                )
            if formula.get("plain_explanation"):
                story.append(Paragraph(escape(formula["plain_explanation"]), styles["ExportBodyText"]))
            symbols = formula.get("symbols") or {}
            for symbol, meaning in symbols.items():
                story.append(
                    Paragraph(
                        f"• {escape(str(symbol))}: {escape(str(meaning))}",
                        styles["ExportMetaText"],
                    )
                )
            if formula.get("importance"):
                story.append(
                    Paragraph(
                        f"<b>Why it matters:</b> {escape(formula['importance'])}",
                        styles["ExportBodyText"],
                    )
                )
            story.append(Spacer(1, 0.1 * inch))
        story.append(Spacer(1, 0.08 * inch))

    def _append_pdf_results_view(self, story: List[Any], styles: Any, heading: str, results_view: Optional[Dict[str, Any]]) -> None:
        normalized = results_view or {}
        if not normalized:
            return
        has_content = any(
            normalized.get(key)
            for key in ("evaluation_setup", "results_summary", "strongest_evidence", "caveats")
        )
        if not has_content:
            return

        story.append(Paragraph(f"<b>{escape(heading)}</b>", styles["SubHeading"]))
        if normalized.get("evaluation_setup"):
            story.append(
                Paragraph(
                    f"<b>Evaluation setup:</b> {escape(str(normalized['evaluation_setup']))}",
                    styles["ExportBodyText"],
                )
            )
        if normalized.get("results_summary"):
            story.append(
                Paragraph(
                    f"<b>What the evidence says:</b> {escape(str(normalized['results_summary']))}",
                    styles["ExportBodyText"],
                )
            )
        strongest_evidence = [item for item in (normalized.get("strongest_evidence") or []) if item]
        if strongest_evidence:
            story.append(Paragraph("<b>Strongest evidence</b>", styles["ExportBodyText"]))
            for item in strongest_evidence:
                story.append(Paragraph(f"• {escape(str(item))}", styles["ExportMetaText"]))
        caveats = [item for item in (normalized.get("caveats") or []) if item]
        if caveats:
            story.append(Paragraph("<b>Evidence caveats</b>", styles["ExportBodyText"]))
            for item in caveats:
                story.append(Paragraph(f"• {escape(str(item))}", styles["ExportMetaText"]))
        story.append(Spacer(1, 0.12 * inch))

    def _append_pdf_artifact_interpretations(self, story: List[Any], styles: Any, heading: str, items: Optional[List[Dict[str, Any]]]) -> None:
        normalized = [item for item in (items or []) if item.get("what_it_shows") or item.get("why_it_matters")]
        if not normalized:
            return
        story.append(Paragraph(f"<b>{escape(heading)}</b>", styles["SubHeading"]))
        for item in normalized:
            label = item.get("label") or item.get("artifact_type") or "Artifact"
            artifact_type = item.get("artifact_type")
            section_title = item.get("section_title")
            confidence = item.get("confidence")
            title_parts = [str(label)]
            if artifact_type:
                title_parts.append(f"({artifact_type})")
            story.append(Paragraph(f"<b>{escape(' '.join(title_parts))}</b>", styles["ExportBodyText"]))
            meta_parts = []
            if section_title:
                meta_parts.append(f"Section: {section_title}")
            if confidence:
                meta_parts.append(f"Confidence: {confidence}")
            if meta_parts:
                story.append(Paragraph(escape(" | ".join(meta_parts)), styles["ExportMetaText"]))
            if item.get("what_it_shows"):
                story.append(
                    Paragraph(
                        f"<b>What it shows:</b> {escape(str(item['what_it_shows']))}",
                        styles["ExportBodyText"],
                    )
                )
            if item.get("why_it_matters"):
                story.append(
                    Paragraph(
                        f"<b>Why it matters:</b> {escape(str(item['why_it_matters']))}",
                        styles["ExportBodyText"],
                    )
                )
            if item.get("missing_context"):
                story.append(
                    Paragraph(
                        f"<b>Missing context:</b> {escape(str(item['missing_context']))}",
                        styles["ExportMetaText"],
                    )
                )
            story.append(Spacer(1, 0.1 * inch))
        story.append(Spacer(1, 0.08 * inch))

    def _append_pdf_figure_section(self, story: List[Any], styles: Any, heading: str, figures: Optional[List[Dict[str, Any]]]) -> None:
        normalized = [figure for figure in (figures or []) if figure.get("caption")]
        if not normalized:
            return
        story.append(Paragraph(f"<b>{escape(heading)}</b>", styles["SubHeading"]))
        for figure in normalized:
            label = figure.get("label") or "Figure"
            page = figure.get("page")
            page_suffix = f" (page {page + 1})" if isinstance(page, int) else ""
            story.append(
                Paragraph(
                    f"<b>{escape(str(label))}{escape(page_suffix)}:</b> {escape(figure['caption'])}",
                    styles["ExportBodyText"],
                )
            )
        story.append(Spacer(1, 0.12 * inch))

    def _append_pdf_table_section(self, story: List[Any], styles: Any, heading: str, tables: Optional[List[Dict[str, Any]]]) -> None:
        normalized = [table for table in (tables or []) if table.get("rows")]
        if not normalized:
            return
        story.append(Paragraph(f"<b>{escape(heading)}</b>", styles["SubHeading"]))
        for table in normalized:
            title = table.get("title") or "Table"
            page = table.get("page")
            page_suffix = f" (page {page + 1})" if isinstance(page, int) else ""
            story.append(Paragraph(f"<b>{escape(title)}{escape(page_suffix)}</b>", styles["ExportBodyText"]))
            preview_rows = table.get("rows", [])[:6]
            for row in preview_rows:
                row_text = " | ".join((cell or "—").strip() for cell in row)
                story.append(Paragraph(escape(row_text), styles["ExportMetaText"]))
            story.append(Spacer(1, 0.08 * inch))
        story.append(Spacer(1, 0.08 * inch))

    def _append_pdf_graph_section(self, story: List[Any], styles: Any, heading: str, knowledge_graph: Dict[str, Any]) -> None:
        nodes = knowledge_graph.get("nodes") or []
        edges = knowledge_graph.get("edges") or []
        if not nodes and not edges:
            return

        story.append(Paragraph(f"<b>{escape(heading)}</b>", styles["SubHeading"]))
        if nodes:
            story.append(Paragraph("<b>Key concepts</b>", styles["ExportBodyText"]))
            for node in nodes[:12]:
                label = node.get("label") or node.get("id") or "Concept"
                category = node.get("category")
                definition = node.get("definition")
                title = label if not category else f"{label} ({category})"
                story.append(Paragraph(f"• {escape(title)}", styles["ExportBodyText"]))
                if definition:
                    story.append(Paragraph(escape(definition), styles["ExportMetaText"]))
        if edges:
            story.append(Spacer(1, 0.08 * inch))
            story.append(Paragraph("<b>Key relationships</b>", styles["ExportBodyText"]))
            for edge in edges[:16]:
                source = edge.get("source", "source")
                relation = edge.get("type", "relates to")
                target = edge.get("target", "target")
                story.append(
                    Paragraph(
                        f"• {escape(str(source))} {escape(str(relation))} {escape(str(target))}",
                        styles["ExportMetaText"],
                    )
                )
        story.append(Spacer(1, 0.12 * inch))

    def _append_markdown_section(self, lines: List[str], heading: str, content: Optional[str]) -> None:
        if not content:
            return
        lines.extend([f"## {heading}", "", content.strip(), ""])

    def _append_markdown_list_section(self, lines: List[str], heading: str, items: Optional[Iterable[str]]) -> None:
        normalized = [item.strip() for item in (items or []) if item and item.strip()]
        if not normalized:
            return
        lines.extend([f"## {heading}", ""])
        lines.extend([f"- {item}" for item in normalized])
        lines.append("")

    def _append_markdown_section_breakdown(self, lines: List[str], heading: str, sections: Optional[List[Dict[str, Any]]]) -> None:
        normalized = [section for section in (sections or []) if section.get("title") or section.get("summary")]
        if not normalized:
            return
        lines.extend([f"## {heading}", ""])
        for section in normalized:
            lines.append(f"### {section.get('title', 'Untitled section')}")
            lines.append("")
            if section.get("summary"):
                lines.append(section["summary"].strip())
                lines.append("")
            if section.get("why_it_matters"):
                lines.append(f"**Why it matters:** {section['why_it_matters'].strip()}")
                lines.append("")

    def _append_markdown_terms(self, lines: List[str], heading: str, terms: Optional[List[Dict[str, Any]]]) -> None:
        normalized = [term for term in (terms or []) if term.get("term")]
        if not normalized:
            return
        lines.extend([f"## {heading}", ""])
        for term in normalized:
            category = f" ({term['category']})" if term.get("category") else ""
            lines.append(f"- **{term['term']}**{category}: {term.get('definition', '').strip()}")
        lines.append("")

    def _append_markdown_formulas(self, lines: List[str], heading: str, formulas: Optional[List[Dict[str, Any]]]) -> None:
        normalized = [formula for formula in (formulas or []) if formula.get("latex") or formula.get("plain_explanation")]
        if not normalized:
            return
        lines.extend([f"## {heading}", ""])
        for formula in normalized:
            if formula.get("latex"):
                lines.append(f"### `{formula['latex']}`")
                lines.append("")
            if formula.get("plain_explanation"):
                lines.append(formula["plain_explanation"].strip())
                lines.append("")
            symbols = formula.get("symbols") or {}
            if symbols:
                lines.append("**Symbols**")
                lines.append("")
                for symbol, meaning in symbols.items():
                    lines.append(f"- `{symbol}`: {meaning}")
                lines.append("")
            if formula.get("importance"):
                lines.append(f"**Why it matters:** {formula['importance'].strip()}")
                lines.append("")

    def _append_markdown_results_view(self, lines: List[str], heading: str, results_view: Optional[Dict[str, Any]]) -> None:
        normalized = results_view or {}
        if not normalized:
            return
        has_content = any(
            normalized.get(key)
            for key in ("evaluation_setup", "results_summary", "strongest_evidence", "caveats")
        )
        if not has_content:
            return

        lines.extend([f"## {heading}", ""])
        if normalized.get("evaluation_setup"):
            lines.append(f"**Evaluation setup:** {str(normalized['evaluation_setup']).strip()}")
            lines.append("")
        if normalized.get("results_summary"):
            lines.append(f"**What the evidence says:** {str(normalized['results_summary']).strip()}")
            lines.append("")
        strongest_evidence = [item for item in (normalized.get("strongest_evidence") or []) if item]
        if strongest_evidence:
            lines.append("### Strongest evidence")
            lines.append("")
            lines.extend([f"- {str(item).strip()}" for item in strongest_evidence])
            lines.append("")
        caveats = [item for item in (normalized.get("caveats") or []) if item]
        if caveats:
            lines.append("### Evidence caveats")
            lines.append("")
            lines.extend([f"- {str(item).strip()}" for item in caveats])
            lines.append("")

    def _append_markdown_artifact_interpretations(self, lines: List[str], heading: str, items: Optional[List[Dict[str, Any]]]) -> None:
        normalized = [item for item in (items or []) if item.get("what_it_shows") or item.get("why_it_matters")]
        if not normalized:
            return
        lines.extend([f"## {heading}", ""])
        for item in normalized:
            label = item.get("label") or item.get("artifact_type") or "Artifact"
            artifact_type = f" ({item['artifact_type']})" if item.get("artifact_type") else ""
            lines.append(f"### {label}{artifact_type}")
            lines.append("")
            if item.get("section_title"):
                lines.append(f"**Section:** {str(item['section_title']).strip()}")
                lines.append("")
            if item.get("confidence"):
                lines.append(f"**Confidence:** {str(item['confidence']).strip()}")
                lines.append("")
            if item.get("what_it_shows"):
                lines.append(f"**What it shows:** {str(item['what_it_shows']).strip()}")
                lines.append("")
            if item.get("why_it_matters"):
                lines.append(f"**Why it matters:** {str(item['why_it_matters']).strip()}")
                lines.append("")
            if item.get("missing_context"):
                lines.append(f"**Missing context:** {str(item['missing_context']).strip()}")
                lines.append("")

    def _append_markdown_figures(self, lines: List[str], heading: str, figures: Optional[List[Dict[str, Any]]]) -> None:
        normalized = [figure for figure in (figures or []) if figure.get("caption")]
        if not normalized:
            return
        lines.extend([f"## {heading}", ""])
        for figure in normalized:
            label = figure.get("label") or "Figure"
            page = figure.get("page")
            page_suffix = f" (page {page + 1})" if isinstance(page, int) else ""
            lines.append(f"- **{label}{page_suffix}:** {figure['caption']}")
        lines.append("")

    def _append_markdown_tables(self, lines: List[str], heading: str, tables: Optional[List[Dict[str, Any]]]) -> None:
        normalized = [table for table in (tables or []) if table.get("rows")]
        if not normalized:
            return
        lines.extend([f"## {heading}", ""])
        for table in normalized:
            title = table.get("title") or "Table"
            page = table.get("page")
            page_suffix = f" (page {page + 1})" if isinstance(page, int) else ""
            lines.append(f"### {title}{page_suffix}")
            lines.append("")
            preview_rows = table.get("rows", [])[:6]
            for row in preview_rows:
                lines.append(f"- {' | '.join((cell or '—').strip() for cell in row)}")
            lines.append("")

    def _append_markdown_graph(self, lines: List[str], heading: str, knowledge_graph: Dict[str, Any]) -> None:
        nodes = knowledge_graph.get("nodes") or []
        edges = knowledge_graph.get("edges") or []
        if not nodes and not edges:
            return
        lines.extend([f"## {heading}", ""])
        if nodes:
            lines.extend(["### Key concepts", ""])
            for node in nodes[:12]:
                label = node.get("label") or node.get("id") or "Concept"
                category = f" ({node['category']})" if node.get("category") else ""
                definition = f": {node['definition']}" if node.get("definition") else ""
                lines.append(f"- **{label}**{category}{definition}")
            lines.append("")
        if edges:
            lines.extend(["### Key relationships", ""])
            for edge in edges[:16]:
                lines.append(f"- `{edge.get('source', 'source')}` {edge.get('type', 'relates to')} `{edge.get('target', 'target')}`")
            lines.append("")

    def _paragraphs(self, content: str) -> List[str]:
        return [paragraph.strip() for paragraph in content.split("\n") if paragraph.strip()]

    def _paper_source_url(self, paper: Dict[str, Any]) -> Optional[str]:
        if paper.get("source_url"):
            return str(paper["source_url"])
        arxiv_id = (paper.get("arxiv_id") or "").strip()
        if arxiv_id:
            return f"https://arxiv.org/abs/{arxiv_id}"
        return None
